# Generated by Django 5.1.7 on 2025-04-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teams_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='Name',
            new_name='name',
        ),
    ]
